/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kharisma
 */
public class bayar extends javax.swing.JFrame {
String paketheavly;
String paketsnack;
int hargaheavly;
int hargasnack;
int jumlahheavly;
int jumlahsnack;
int jumlahhargaheavly;
int jumlahhargasnack;
int jumlahharga1;
int jumlahharga2;
int potonganharga;
int potonganharga2;
int total;
    /**
     * Creates new form bayar
     */
    public bayar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxheavly = new javax.swing.JComboBox<>();
        boxsnack = new javax.swing.JComboBox<>();
        txsatuan = new javax.swing.JTextField();
        txsatuan2 = new javax.swing.JTextField();
        txtotal = new javax.swing.JTextField();
        btok = new javax.swing.JButton();
        cmbbeli = new javax.swing.JComboBox<>();
        cmbbeli2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        diskon2 = new javax.swing.JTextField();
        txtotal2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txakhir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        txtjumlah2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Paket");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 110, 34));

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga Satuan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 160, 35));

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Beli");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 140, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 170, 38));

        boxheavly.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        boxheavly.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "Nayam(nasi putih)", "Nayam(nasi merah)","Nayam(nasi bakar)", "Nakan(nasi putih)", "Nakan(basi merah)", "Nakan(nasi bakar)", "Nasea(nasi putih)", "Nasea(nasi merah)", "NaDa(nasi putih)", "NaDa(nasi merah)"}));
        boxheavly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxheavlyActionPerformed(evt);
            }
        });
        getContentPane().add(boxheavly, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 182, 37));

        boxsnack.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        boxsnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "Random Asin", "Random Manis", "Random " }));
        boxsnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxsnackActionPerformed(evt);
            }
        });
        getContentPane().add(boxsnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 163, 182, 35));

        txsatuan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txsatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 180, 35));

        txsatuan2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txsatuan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 190, 36));

        txtotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 180, 38));

        btok.setBackground(new java.awt.Color(51, 0, 0));
        btok.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        btok.setForeground(new java.awt.Color(255, 255, 255));
        btok.setText("Ok");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });
        getContentPane().add(btok, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 110, 48));

        cmbbeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "1", "5", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        cmbbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbeliActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 128, 36));

        cmbbeli2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        cmbbeli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbeli2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbeli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 265, 128, 36));

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Potongan Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 180, -1));
        getContentPane().add(diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 180, 34));
        getContentPane().add(diskon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 319, 180, 34));

        txtotal2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 371, 180, 37));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Akhir");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 140, 38));

        txakhir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 268, 42));

        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 151, 38));
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 180, 38));
        getContentPane().add(txtjumlah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 421, 180, 38));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pricE (2).png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxheavlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxheavlyActionPerformed
        // TODO add your handling code here:
        if (boxheavly.getSelectedIndex() ==1 ){
            hargaheavly = 20000; 
        } else if(boxheavly.getSelectedIndex() == 2 ){
            hargaheavly = 25000;
        }else if(boxheavly.getSelectedIndex() == 3 ){
            hargaheavly = 20000;  
        }else if(boxheavly.getSelectedIndex() == 4 ){
            hargaheavly = 20000;
        }else if(boxheavly.getSelectedIndex() == 5 ){
            hargaheavly = 25000;
        }else if(boxheavly.getSelectedIndex() == 6 ){
            hargaheavly = 20000;
        }else if(boxheavly.getSelectedIndex() == 7 ){
            hargaheavly = 25000;
        }else if(boxheavly.getSelectedIndex() == 8 ){
            hargaheavly = 30000;
        }else if(boxheavly.getSelectedIndex() == 9 ){
            hargaheavly = 25000;
        }else if(boxheavly.getSelectedIndex() == 10 ){
            hargaheavly = 30000;
        }
        txsatuan.setText(String.valueOf(hargaheavly));
        
    }//GEN-LAST:event_boxheavlyActionPerformed

    
    private void boxsnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxsnackActionPerformed
        // TODO add your handling code here:
         if (boxsnack.getSelectedIndex() == 1 ){
            hargasnack = 10000; 
        } else if(boxsnack.getSelectedIndex() == 2 ){
            hargasnack = 10000;
        }else if(boxsnack.getSelectedIndex() == 3 ){
            hargasnack = 10000;  
        }
          txsatuan2.setText(String.valueOf(hargasnack));
          
    }//GEN-LAST:event_boxsnackActionPerformed

    private void cmbbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbeliActionPerformed
        // TODO add your handling code here:
        jumlahheavly = (int) cmbbeli.getSelectedIndex();
        if(jumlahheavly <= 10 ){
            potonganharga = 500;
        }else if(jumlahheavly > 10 && jumlahheavly < 50 ){
            potonganharga = 1000;
        }else if(jumlahheavly > 50 && jumlahheavly < 100 ){
            potonganharga = 1500;
        }
        
        diskon.setText(String.valueOf(potonganharga));
        
        jumlahhargaheavly = hargaheavly * jumlahheavly;
        txtotal.setText(String.valueOf(jumlahhargaheavly));
        
        jumlahharga1 = jumlahhargaheavly - potonganharga;
        txtjumlah.setText(String.valueOf(jumlahharga1));
    }//GEN-LAST:event_cmbbeliActionPerformed

    private void cmbbeli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbeli2ActionPerformed
        // TODO add your handling code here:
        jumlahsnack = (int) cmbbeli2.getSelectedIndex();
        if(jumlahsnack <= 20 ){
            potonganharga2 = 500;
        }else if(jumlahsnack > 20 && jumlahsnack < 60 ){
            potonganharga2 = 1000;
        }else if(jumlahheavly > 60 && jumlahsnack < 100 ){
            potonganharga2 = 1200;
        }
        diskon2.setText(String.valueOf(potonganharga2));
        
        jumlahhargasnack = hargasnack * jumlahsnack;
        txtotal2.setText(String.valueOf(jumlahhargasnack));
        
        jumlahharga2 = jumlahhargasnack - potonganharga2;
        txtjumlah2.setText(String.valueOf(jumlahharga2));
        
        total = jumlahharga1 + jumlahharga2;
        txakhir.setText(String.valueOf(total));
    }//GEN-LAST:event_cmbbeli2ActionPerformed

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        // TODO add your handling code here:
            akhir ak = new akhir();
            ak.setVisible(true);
            ak.pack();
            ak.setLocationRelativeTo(null);
            ak.setDefaultCloseOperation(register.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_btokActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxheavly;
    private javax.swing.JComboBox<String> boxsnack;
    private javax.swing.JButton btok;
    private javax.swing.JComboBox<String> cmbbeli;
    private javax.swing.JComboBox<String> cmbbeli2;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField diskon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txakhir;
    private javax.swing.JTextField txsatuan;
    private javax.swing.JTextField txsatuan2;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtjumlah2;
    private javax.swing.JTextField txtotal;
    private javax.swing.JTextField txtotal2;
    // End of variables declaration//GEN-END:variables
}
